### ISSUE TITLE
Doesn’t work with tsc’s pretty flag

### ISSUE THREAD

**Issue by tomaba** [gilamran/tsc-watch#25]
The error regex is wrong.

**Comment by tomaba** [comment]
If you set "pretty": true in tsconfig.json compiler options the errors printed in a different way.
As you can see it runs the program even though the compiler failed.
This is because the error string doesn't look like `\(\d+,\d+\): error TS\d+:/` but it seperates the error with : and has the terminal coloring symbols.

![image](https://user-images.githubusercontent.com/9085658/38459884-4f1e22c0-3ab8-11e8-8d9b-a7b9b8e591ac.png)

**Comment by gilamran** [comment]
Thanks for the info.
Fixed on version 1.0.18v

**Comment by tomaba** [comment]
Sorry to bother but it's still doesn't work on tsc 2.8.1 (tsc-watch 1.0.18) because there is no (\d+,\d+) in the error line.
As you can see in the above photo it's like [color]file:[color]number[color]:[color]number...
Which means the regex should be something like .*?\d+:.*?\d+.*? - .*?error.*? TS\d+ (I used .*? is because I don't know exactly the regex for ANSI coloring codes).
BTW you can use https://www.npmjs.com/package/strip-ansi to strip it (Haven't testsed).
Hope this helps. And thanks for the quick response and for this package :)

**Comment by gilamran** [comment]
weird, I'll recheck.
Thanks

**Comment by gilamran** [comment]
Fixed, I was using an older version of typescript.
