### ISSUE TITLE
onSuccess is executed even when the compilation had errors

### ISSUE THREAD

**Issue by tombousso** [gilamran/tsc-watch#32]
Caused by https://github.com/gilamran/tsc-watch/commit/6c3de287fad51bfb71a9674c2e715514cf36c19b

`hadErrors` is no longer being checked

Probably need

    killAllSuccessProcesses().then(() => {
      if (hadErrors) return;
      Signal.emitSuccess();
.

    killFailureProcess().then(() => {
      if (!hadErrors) return;
      Signal.emitFail();

**Comment by gilamran** [comment]
Cool! thanks for finding this one!
Fixed and published on version 1.0.25

**Comment by tombousso** [comment]
https://github.com/gilamran/tsc-watch/commit/72a58ae461769d22ca6784b37f968c074f4d73fc still doesn't fix the issue because the `if (emitSuccess) {` only surrounds `Singal.emitSuccess()`

**Comment by gilamran** [comment]
@tombousso I don't see what's the problem with that...
We want to send the signal, and exit all the processes...
Can you please provide a way for me to reproduce the issue on my machine?

**Comment by tombousso** [comment]
The problem is that the `killAllProcesses` function will end up calling `runCommand(onSuccessCommand)` even if `hadErrors` is true.

You can reproduce by running tsc-watch with `--onSuccess` and creating a compiler error.

**Comment by gilamran** [comment]
@tombousso Right, that's what happens when you fix without thinking 🤕 
Fixed on version 1.0.26
